version: '3.8'

services:
    laravel_app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        environment:
            - APP_ENV=local
            - APP_KEY=
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
        depends_on:
            - mysql
        networks:
            - laravel_network

    laravel_webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - laravel_app
        networks:
            - laravel_network

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
